name: "TFTP server"
description: "Expose a chosen grub configuration on a TFTP server"
version: "1.0.0"
slug: "grub_tftp"
init: false
stdin: true
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  69/udp: 69

options:
    adress_mac: 'MAC_ADRESS'
    configs:
      - id: default
        grub_default: 0
        grub_timeout: 10
      - id: 'ubuntu'
        grub_default: 0
        grub_timeout: 2
      - id: 'windows'
        grub_default: 2
        grub_timeout: 2
      - id: 'bios'
        grub_default: 3
        grub_timeout: 2
schema:
  adress_mac: str
  configs:
    - id: str
      grub_default: int
      grub_timeout: int